#!/usr/bin/env bash

set -x
if [[ $# -eq 1 ]]; then
  selected=$1
else
  selected=$(find ~/projects/work ~/projects/personal -mindepth 1 -maxdepth 1 -type d | fzf --preview 'bat --color=always {}/README.md 2>/dev/null||bat --color=always {}/readme.md 2>/dev/null||tree -C {}' )
fi

if [[ -z $selected ]]; then    
  exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
  tmux new-session -s $selected_name -c $selected
  exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
  tmux new-session -ds $selected_name -c $selected
  tmux set-environment -t $selected_name TMUX_SESSION_ROOT_DIR $selected
fi

tmux switch-client -t $selected_name

if [[ -e ${selected}/.tmux-setup.sh ]]; then
  source ${selected}/.tmux-setup.sh ${selected_name}
fi


# vim: set filetype=bash :
